---
title: VOLGA seminar
timezone: Europe/Moscow
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: your-email@domain.com
description: 'This is web page of weekly VOLGA seminar hosting at Sternberg Astronomical
  Institute.

'
baseurl: "/volga"
markdown: kramdown
paginate: 6
gems:
- jekyll-paginate
